from __future__ import annotations

import uuid
from typing import Protocol

from app.domain.entities import Account, Category, RefreshSession, Transaction, User


class UserRepository(Protocol):
    async def get_by_id(self, user_id: uuid.UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_google_sub(self, google_sub: str) -> User | None: ...
    async def create(self, user: User) -> User: ...


class AccountRepository(Protocol):
    async def create(self, account: Account) -> Account: ...
    async def get_for_user(self, account_id: uuid.UUID, user_id: uuid.UUID) -> Account | None: ...
    async def list_for_user(self, user_id: uuid.UUID) -> list[Account]: ...
    async def update(self, account: Account) -> Account: ...


class CategoryRepository(Protocol):
    async def create(self, category: Category) -> Category: ...
    async def get_for_user(self, category_id: uuid.UUID, user_id: uuid.UUID) -> Category | None: ...
    async def list_for_user(self, user_id: uuid.UUID) -> list[Category]: ...
    async def update(self, category: Category) -> Category: ...
    async def delete_for_user(self, category_id: uuid.UUID, user_id: uuid.UUID) -> bool: ...


class TransactionRepository(Protocol):
    async def create(self, transaction: Transaction) -> Transaction: ...
    async def get_for_user(
        self,
        transaction_id: uuid.UUID,
        user_id: uuid.UUID,
        *,
        include_deleted: bool = False,
    ) -> Transaction | None: ...
    async def list_for_user(self, user_id: uuid.UUID, *, include_deleted: bool = False) -> list[Transaction]: ...
    async def update(self, transaction: Transaction) -> Transaction: ...
    async def soft_delete_for_user(self, transaction_id: uuid.UUID, user_id: uuid.UUID) -> bool: ...
    async def restore_for_user(self, transaction_id: uuid.UUID, user_id: uuid.UUID) -> bool: ...


class RefreshSessionRepository(Protocol):
    async def create(self, session: RefreshSession) -> RefreshSession: ...
    async def get_by_jti(self, jti: str) -> RefreshSession | None: ...
    async def revoke(self, jti: str) -> None: ...
